# Generated by Django 4.0.1 on 2022-01-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbot_app', '0002_poempoem'),
    ]

    operations = [
        migrations.CreateModel(
            name='mbkk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.IntegerField()),
                ('mbname', models.CharField(max_length=256)),
                ('mbstyle', models.CharField(max_length=64)),
                ('mbtakeaway', models.CharField(max_length=64)),
                ('mblat', models.FloatField()),
                ('mblng', models.FloatField()),
                ('mburl', models.CharField(max_length=256)),
                ('mbimgurl', models.CharField(max_length=256)),
                ('mbaddress', models.CharField(max_length=256)),
                ('mbprice', models.CharField(max_length=64)),
                ('mbview', models.TextField()),
                ('mbcontact', models.CharField(max_length=32)),
                ('mbservice', models.TextField()),
                ('mbaward', models.CharField(max_length=256)),
            ],
        ),
    ]
