# Generated by Django 4.0.1 on 2022-01-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbot_app', '0003_mbkk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mbkk',
            old_name='mbcontact',
            new_name='mbfoodstyle',
        ),
        migrations.RenameField(
            model_name='mbkk',
            old_name='mbprice',
            new_name='mbuserid',
        ),
        migrations.RemoveField(
            model_name='mbkk',
            name='mbaddress',
        ),
        migrations.RemoveField(
            model_name='mbkk',
            name='mbaward',
        ),
        migrations.RemoveField(
            model_name='mbkk',
            name='mbid',
        ),
        migrations.RemoveField(
            model_name='mbkk',
            name='mbimgurl',
        ),
        migrations.RemoveField(
            model_name='mbkk',
            name='mblat',
        ),
        migrations.RemoveField(
            model_name='mbkk',
            name='mblng',
        ),
        migrations.RemoveField(
            model_name='mbkk',
            name='mbname',
        ),
        migrations.RemoveField(
            model_name='mbkk',
            name='mbservice',
        ),
        migrations.RemoveField(
            model_name='mbkk',
            name='mbstyle',
        ),
        migrations.RemoveField(
            model_name='mbkk',
            name='mbtakeaway',
        ),
        migrations.RemoveField(
            model_name='mbkk',
            name='mburl',
        ),
        migrations.RemoveField(
            model_name='mbkk',
            name='mbview',
        ),
    ]
