"""
Django settings for f_bot project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import django_heroku

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$a&3c*486b2^)3@z_8f1oxuhlh$k8x=yuyh@m672*v^%cfiome'

# LINE_CHANNEL_ACCESS_TOKEN = 'b4mw1HF6iYnAIMfSBUworWGdTS+E2T8MtVcLn/ZYJtEG+9Yh7Yg+OPjaaw0nb+NGJQOgdexyKSGdkT/BgHdPjvM9SMniseL13BTvx6r8t3x9BC87GSJ58v+YcggaRmDGh3/2aiMs1BT8fSTrAslJsQdB04t89/1O/w1cDnyilFU='
# LINE_CHANNEL_SECRET = 'd048d0a4c64643f17c19f5df28b86c85'

# --------------------------------

# 2022-01-27 Bkk Michelin Ver 1
# LINE_CHANNEL_ACCESS_TOKEN = 'aqekULWhc+iZEpitXvPGBKvmGm99S64/JmptZPVX+s/aRuNN1z2dhorYaFgh0NIFlZQsTKSA+WId1df14vKR55kmEH0BcNPCyv7Kijox4G47MDH1ufxHPQlm0UrNcqWkm4fOVmaa/IAdAS66KTGeHgdB04t89/1O/w1cDnyilFU='
# LINE_CHANNEL_SECRET = 'ad1bdcd04c0c3e13a3385213f83954e9'
# 2022-01-27 Bkk Michelin Ver 1

# 2023-07-24 Bkk Schools Ver 1
LINE_CHANNEL_ACCESS_TOKEN = 'qyzmb2ClC0F3+3TjWkbMCwAxmnuJ+vm41mwLvKMolin45Oj9hJk9ypM+0J0FyKhFP/cfo9B2RmBdi+BIR2xs9/dZIA4l87aRUESB5ZfLQGZ+wnv8ErsI/lXt83wo5eBllXdPnOSRrVVYtqO2hf4VTwdB04t89/1O/w1cDnyilFU='
LINE_CHANNEL_SECRET = '2befd595307c5f05af1ce8584ac55f8e'
# 2023-07-24 Bkk Schools Ver 1

# 2022-01-27 Bkk Ver 1
# ---------------------
# 2022-01-27 CM Ver 1

# LINE_CHANNEL_ACCESS_TOKEN = '42bWU8Oyoih1zd8PdOdMVEFg8/+c8XLZ1leC79THDpl+3dab0p26dVW25NXOJ5pqcPdpRCEXVITrMiykMBliTnthP9hJ/g59G3cbj1fXXaMnA3Yp7vvcO2qeHDb4+z3SVXmjIqhbJjMq6GkDUa+AkQdB04t89/1O/w1cDnyilFU='
# LINE_CHANNEL_SECRET = '39e9f05e792c1cce193eb75bb8ad50dc'

# 2022-01-27 CM Ver 1

# --------------------------------


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fbot_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'f_bot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],#新增templates資料夾路徑
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'f_bot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',  #PostgreSQL
#         'NAME': 'dbstraybirds',  #資料庫名稱
#         'USER': 'limin',  #資料庫帳號
#         'PASSWORD': 'odoopwd',  #資料庫密碼
#         'HOST': 'localhost',  #Server(伺服器)位址
#         'PORT': '5432'  #PostgreSQL Port號
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/


LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICILES_DIRS = [
    os.path.join(BASE_DIR,'static/')#加入static路徑
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#-----------------2021-09-06

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/') #加入 media 路徑

#-----------------2021-09-06

django_heroku.settings(locals())
