locations = [
"Ruamrudee International School Ratchapruek Campus Bangkok",
]

# locations = [
# "Bangkok Patana School",
# "NIST International School Bangkok",
# "International School Bangkok",
# "Shrewsbury International School Bangkok",
# "Harrow International School Bangkok",
# "International Community School Bangkok",
# "Brighton College International School Bangkok",
# "St.Andrews International School Bangkok",
# "Bangkok Prep School",
# "Concordian International School Bangkok",
# "Ruamrudee International School Bangkok",
# "KIS International School Bangkok",
# "St.Andrews Sukhumvit 107 Shool Bangkok",
# "Bromsgrove International School Bangkok",
# "The Regent's International School Bangkok",
# "Berkeley International School Bangkok",
# "Singapore International School of Bangkok",
# "The American School of Bangkok",
# "Charter International School Bangkok",
# "St.Stephen's International School Bangkok",
# "Canadian International School Bangkok",
# "Anglo Singapore International School Bangkok",
# "Garden International School Bangkok",
# "Wells International School Bangkok",
# "Ascot International School Bangkok",
# "RBIS-Rasami British International School Bangkok",
# "Bangkok Christian International School",
# "Keera-Pat International School Bangkok",
# "Morden International School Bangkok",
# "Trinity International School Bangkok",
# "Pan-Asia International School Bangkok",
# "International Pioneers School Bangkok",
# "Traill International School Bangkok",
# "Heathfield International School Bangkok",
# "Ramkhamhaeng Advent International School Bangkok",
# "Thai-Singapore International School Bangkok",
# "Ekkamai International School Bangkok",
# "Niva International School Bangkok",
# "New Sathorn International School Bangkok",
# "Kincaid International School of Bangkok",
# "Thai-Chinese International School Bangkok",
# "King's College Bangkok",
# "Wellington College Bangkok",
# "Basis International School Bangkok",
# "Shrewsbury City Campus Bangkok",
# "Denla British School Bangkok",
# "Verso School Bangkok",
# "Dprep Bangkok School ",
# "Raffles American International School Bangkok",
# "Ruamrudee International School Ratchapruek Campus Bangkok",
# "Mandarin International School Bangkok"
# ]

